clone_folder: "c:\\WORK"

branches:
  only:
    - master

services:
  - postgresql96

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
    PGUSER: postgres
    PGPASSWORD: Password12!
    PGPORT: "5432"
    DATABASE_CONNSTRING: appveyor
  matrix:
    # 64 bit builds
    - GHCVER: "8.8.1"
      CHOCOPTS:
    - GHCVER: "8.6.5"
      CHOCOPTS:
    - GHCVER: "8.4.4"
      CHOCOPTS:
    - GHCVER: "8.2.2"
      CHOCOPTS:
    - GHCVER: "8.0.2"
      CHOCOPTS:
    - GHCVER: "7.10.3.2"
      CHOCOPTS:

    # Fails to link
    #
    # - GHCVER: "7.8.4.1"
    #  CHOCOPTS:

    # 32 bit builds

    # Linker errors...

    # - GHCVER: "8.6.5"
    #   CHOCOPTS: --forcex86
    # - GHCVER: "8.4.4"
    #   CHOCOPTS: --forcex86
    # - GHCVER: "8.2.2"
    #   CHOCOPTS: --forcex86

    # older segfault?

cache:
- "C:\\SR"

install:
 - "choco install -y ghc --version %GHCVER% %CHOCOPTS%"
 - "choco install -y cabal %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\ghc\\ghc-%GHCVER%:C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"

 - set PATH=C:\Progra~1\PostgreSQL\9.6\bin\;%PATH%

build: off

test_script:
 - "cabal %CABOPTS% update -v"
 - createdb TestDb
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "move cabal.project.local.win cabal.project.local"

 - "cabal %CABOPTS% v2-build -j1 libs test"
 # - "cabal %CABOPTS% v2-test -j1 all"
 - "cabal %CABOPTS% v2-run test"
 # - "cabal %CABOPTS% v2-run inspection" # only GHC-8.0 (or GHC-8.2+)

 # Build from sdist
 - "rmdir /Q /S dist-newstyle"
 - "cabal v2-sdist"
 - "sh -c 'echo packages: dist-newstyle/sdist/*.tar.gz > cabal.project'"
 - "cabal v2-build -j1 postgresql-simple" # TODO: unfortunately the package name have to be here
